// R1 — Compiled dossier. Doc tree + comments from API.
import * as React from "react";
import { CheckCircle, Download, Send, FileText, ChevronDown, ChevronRight, MessageSquare } from "lucide-react";
import { C } from "../design/tokens";
import { Btn, Chip, Card, Breadcrumb, ScreenCaption } from "../design/primitives";
import { getDocTree, listComments } from "../api/resources";
import { useApi, ErrorBanner, LoadingLabel } from "../api/useApi";
import type { DocTreeNode, Comment } from "../api/types";

const DEMO_PROJECT_ID = "px-102-de";

function formatCommentTime(iso: string): string {
  const d = new Date(iso);
  const today = new Date();
  const sameDay = d.toDateString() === today.toDateString();
  const yesterday = new Date(today); yesterday.setDate(today.getDate() - 1);
  const isYesterday = d.toDateString() === yesterday.toDateString();
  const time = d.toLocaleTimeString([], { hour: "2-digit", minute: "2-digit", hour12: false });
  if (sameDay) return `Today ${time}`;
  if (isYesterday) return `Yesterday ${time}`;
  return d.toISOString().slice(0, 10);
}

function R1RightPanel({ comments, loading, errorMsg }: { comments: Comment[]; loading: boolean; errorMsg: string | null }) {
  const [tab, setTab] = React.useState<"info" | "comments">("comments");
  const unresolved = comments.filter(c => !c.resolved).length;

  return (
    <Card style={{ display: "flex", flexDirection: "column", overflow: "hidden" }}>
      <div style={{ display: "flex", borderBottom: `1px solid ${C.border1}` }}>
        {[{ key: "info", label: "Package info" }, { key: "comments", label: "Comments", badge: unresolved }].map(t => (
          <button key={t.key} onClick={() => setTab(t.key as any)} style={{
            flex: 1, padding: "10px 8px", fontSize: 12, fontWeight: tab === t.key ? 600 : 400,
            color: tab === t.key ? C.brand : C.text3, border: "none", cursor: "pointer",
            borderBottom: `2px solid ${tab === t.key ? C.brand : "transparent"}`,
            backgroundColor: "transparent", fontFamily: "inherit",
            display: "flex", alignItems: "center", justifyContent: "center", gap: 6,
          }}>
            {t.label}
            {t.badge ? (
              <span style={{ width: 16, height: 16, borderRadius: "50%", backgroundColor: tab === t.key ? C.brand : C.border2, color: tab === t.key ? "white" : C.text3, fontSize: 9, fontWeight: 700, display: "inline-flex", alignItems: "center", justifyContent: "center" }}>{t.badge}</span>
            ) : null}
          </button>
        ))}
      </div>

      {tab === "info" && (
        <div style={{ padding: 16, flex: 1 }}>
          {[["Version", "v1.0"], ["Generated by", "Run #4821"], ["Generated at", "2025-11-13 14:22"], ["Total size", "48.3 MB"], ["Page count", "312 pages"], ["Section count", "60 sections"]].map(([k, v]) => (
            <div key={k} style={{ display: "flex", justifyContent: "space-between", padding: "7px 0", borderBottom: `1px solid ${C.border1}`, fontSize: 12 }}>
              <span style={{ color: C.text3 }}>{k}</span>
              <span style={{ fontWeight: 500, color: C.text1 }}>{v}</span>
            </div>
          ))}
        </div>
      )}

      {tab === "comments" && (
        <div style={{ flex: 1, display: "flex", flexDirection: "column", overflow: "hidden" }}>
          <div style={{ flex: 1, overflowY: "auto", padding: 12, display: "flex", flexDirection: "column", gap: 10 }}>
            {loading && <LoadingLabel>Loading comments…</LoadingLabel>}
            {errorMsg && <ErrorBanner message={errorMsg} />}
            {!loading && !errorMsg && comments.length === 0 && (
              <p style={{ fontSize: 12, color: C.text3, fontStyle: "italic" }}>No comments on this dossier yet.</p>
            )}
            {comments.map(c => (
              <div key={c.id} style={{ borderRadius: 6, border: `1px solid ${c.resolved ? C.border1 : C.warn + "80"}`, backgroundColor: c.resolved ? C.bg : "#FFFDF0", padding: 10 }}>
                <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 6 }}>
                  <div style={{ width: 22, height: 22, borderRadius: "50%", backgroundColor: C.brandTint, color: C.brandPressed, display: "flex", alignItems: "center", justifyContent: "center", fontSize: 9, fontWeight: 700, flexShrink: 0 }}>{c.initials}</div>
                  <div style={{ flex: 1, minWidth: 0 }}>
                    <span style={{ fontSize: 11, fontWeight: 600, color: C.text1 }}>{c.author}</span>
                    <span style={{ fontSize: 10, color: C.text3, marginLeft: 6 }}>{formatCommentTime(c.createdAt)}</span>
                  </div>
                  {c.resolved
                    ? <Chip color="success">Resolved</Chip>
                    : <button style={{ fontSize: 10, color: C.brand, background: "none", border: "none", cursor: "pointer", fontFamily: "inherit", flexShrink: 0 }}>Resolve</button>}
                </div>
                <div style={{ fontSize: 11, color: C.text3, marginBottom: 4 }}>
                  <span style={{ fontFamily: "monospace", color: C.brand }}>{c.sectionCode}</span>
                </div>
                <p style={{ fontSize: 12, color: c.resolved ? C.text3 : C.text1, lineHeight: 1.5 }}>{c.text}</p>
              </div>
            ))}
          </div>

          <div style={{ padding: 12, borderTop: `1px solid ${C.border1}`, display: "flex", flexDirection: "column", gap: 8 }}>
            <div style={{ fontSize: 11, color: C.text3 }}>Comment on <span style={{ fontFamily: "monospace", color: C.brand }}>3.2.S.4.2</span></div>
            <textarea readOnly placeholder="Add a comment for the RA Author…" style={{ width: "100%", height: 60, padding: "6px 8px", borderRadius: 4, border: `1px solid ${C.border1}`, fontSize: 12, fontFamily: "inherit", color: C.text1, resize: "none", outline: "none", boxSizing: "border-box" }} />
            <div style={{ display: "flex", justifyContent: "flex-end" }}>
              <Btn variant="primary" style={{ padding: "4px 12px", fontSize: 12 }}><Send size={11} />Post comment</Btn>
            </div>
          </div>
        </div>
      )}
    </Card>
  );
}

function TreeRow({ node, depth }: { node: DocTreeNode; depth: number }) {
  const [open, setOpen] = React.useState(depth === 0 && node.moduleId === "M3");
  const isModule = depth === 0;
  const hasChildren = node.children.length > 0;
  const paddingLeft = 12 + depth * 16;

  return (
    <>
      <div
        onClick={() => hasChildren && setOpen(o => !o)}
        style={{
          display: "flex", alignItems: "center", gap: 6, padding: `${isModule ? 5 : 4}px 12px 4px`, paddingLeft,
          cursor: hasChildren ? "pointer" : "default",
          backgroundColor: node.active ? C.brandTint : (isModule && open ? C.bg : "transparent"),
          borderLeft: node.active ? `2px solid ${C.brand}` : "2px solid transparent",
        }}
      >
        {hasChildren
          ? (open ? <ChevronDown size={isModule ? 12 : 11} color={C.text3} /> : <ChevronRight size={isModule ? 12 : 11} color={C.text3} />)
          : <FileText size={11} color={node.active ? C.brand : C.text3} />}
        {isModule && node.color && (
          <div style={{ width: 18, height: 18, borderRadius: "50%", backgroundColor: node.color, color: "white", fontSize: 9, fontWeight: 700, display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0 }}>{node.moduleId}</div>
        )}
        <span style={{
          fontSize: isModule ? 12 : 11,
          fontWeight: isModule || node.active ? 600 : 400,
          fontFamily: isModule ? undefined : "monospace",
          color: node.active ? C.brand : (isModule ? C.text1 : C.text2),
        }}>
          {isModule ? `${node.moduleId} ${node.label}` : node.code}
        </span>
        {!isModule && <span style={{ fontSize: 11, color: node.active ? C.brandPressed : C.text3, flex: 1, fontFamily: "sans-serif" }}>{node.label}</span>}
        {isModule && <span style={{ flex: 1 }} />}
        {node.comments > 0 && (
          <div style={{ width: isModule ? 15 : 14, height: isModule ? 15 : 14, borderRadius: "50%", backgroundColor: C.warn, color: "white", fontSize: 9, fontWeight: 700, display: "flex", alignItems: "center", justifyContent: "center" }}>{node.comments}</div>
        )}
      </div>
      {open && node.children.map(child => <TreeRow key={child.code} node={child} depth={depth + 1} />)}
    </>
  );
}

export default function R1Screen() {
  const treeState = useApi((sig) => getDocTree(DEMO_PROJECT_ID, sig), []);
  const commentsState = useApi((sig) => listComments(DEMO_PROJECT_ID, sig), []);

  return (
    <div style={{ padding: 24 }}>
      <ScreenCaption id="R1" persona="RAReviewer" />
      <Breadcrumb items={["Projects", "PX-102", "Compiled package v1"]} />
      <div style={{ display: "flex", alignItems: "flex-start", justifyContent: "space-between", marginBottom: 16 }}>
        <h1 style={{ fontSize: 20, fontWeight: 600, color: C.text1 }}>Compiled dossier · PX-102 · Germany · Initial submission</h1>
        <div style={{ display: "flex", gap: 8, flexShrink: 0 }}>
          <Btn variant="secondary"><Download size={13} />Download PDF</Btn>
          <Btn variant="secondary"><FileText size={13} />Export DOCX</Btn>
          <Btn variant="primary"><CheckCircle size={13} />Approve for sign-off</Btn>
        </div>
      </div>

      {treeState.status === "error" && <ErrorBanner message={treeState.error} style={{ marginBottom: 12 }} />}

      <div style={{ display: "grid", gridTemplateColumns: "300px 1fr 260px", gap: 16 }}>
        <Card style={{ padding: "12px 0", overflowY: "auto", maxHeight: 580 }}>
          <div style={{ padding: "0 12px 8px", fontSize: 13, fontWeight: 600, color: C.text1 }}>Document tree</div>
          {treeState.status === "loading" && <LoadingLabel style={{ padding: "0 12px" }}>Loading tree…</LoadingLabel>}
          {treeState.status === "ready" && treeState.data.map(mod => <TreeRow key={mod.code} node={mod} depth={0} />)}
        </Card>

        <div style={{ display: "flex", flexDirection: "column", gap: 12 }}>
          <Card style={{ flex: 1, overflow: "hidden" }}>
            <div style={{ display: "flex", alignItems: "center", gap: 8, padding: "8px 16px", borderBottom: `1px solid ${C.border1}`, backgroundColor: C.bg }}>
              <span style={{ fontSize: 11, color: C.text3, fontFamily: "monospace" }}>M3 › 3.2.S › 3.2.S.4 › </span>
              <span style={{ fontSize: 12, fontWeight: 600, color: C.text1 }}>3.2.S.4.2 Analytical Procedures</span>
              <div style={{ marginLeft: "auto" }}>
                <Btn variant="secondary" style={{ padding: "4px 10px", fontSize: 12 }}><MessageSquare size={12} />Add comment</Btn>
              </div>
            </div>
            <div style={{ padding: 24 }}>
              <div style={{ fontSize: 10, textAlign: "center", marginBottom: 16, paddingBottom: 8, borderBottom: `1px solid ${C.border1}`, color: C.text3 }}>
                PX-102 · Elmiravir · Germany · Initial CTD Submission · Module 3 Quality
              </div>
              <h3 style={{ fontSize: 14, fontWeight: 600, color: C.text1, textAlign: "center", marginBottom: 16, fontFamily: "Georgia, serif" }}>3.2.S.4.2 Analytical Procedures</h3>
              <p style={{ fontSize: 12, lineHeight: 1.8, color: C.text1, fontFamily: "Georgia, serif" }}>
                The analytical procedures for Elmiravir drug substance characterisation have been developed in accordance with ICH Q2(R2) guidelines.{" "}
                <span style={{ backgroundColor: "#FFF9C4", borderBottom: `2px solid ${C.warn}`, cursor: "pointer", position: "relative" }}>
                  High-performance liquid chromatography (HPLC) with UV detection at 254 nm was used as the primary method for purity determination
                  <span style={{ position: "absolute", top: -8, right: -10, width: 16, height: 16, borderRadius: "50%", backgroundColor: C.warn, color: "white", fontSize: 9, fontWeight: 700, display: "inline-flex", alignItems: "center", justifyContent: "center" }}>1</span>
                </span>
                , in compliance with the approved specifications outlined in §3.2.S.4.1.{" "}
                <span style={{ backgroundColor: "#FFF9C4", borderBottom: `2px solid ${C.warn}`, cursor: "pointer", position: "relative" }}>
                  The limit of detection was determined by signal-to-noise methodology as specified in ICH Q2(R2) §4.4.1
                  <span style={{ position: "absolute", top: -8, right: -10, width: 16, height: 16, borderRadius: "50%", backgroundColor: C.warn, color: "white", fontSize: 9, fontWeight: 700, display: "inline-flex", alignItems: "center", justifyContent: "center" }}>2</span>
                </span>
                .
              </p>
              <div style={{ fontSize: 10, textAlign: "center", marginTop: 32, paddingTop: 8, borderTop: `1px solid ${C.border1}`, color: C.text3 }}>
                Confidential — Contoso Pharma GmbH · Document version 1.0 · Generated 2025-11-13
              </div>
            </div>
          </Card>

          <div style={{ display: "flex", gap: 12, flexWrap: "wrap" }}>
            {[{ count: "214", label: "sections", icon: "✅", color: C.success }, { count: "4", label: "warnings", icon: "⚠", color: "#8A6100" }, { count: "0", label: "errors", icon: "✖", color: C.danger }, { count: commentsState.status === "ready" ? String(commentsState.data.filter(c => !c.resolved).length) : "…", label: "unresolved comments", icon: "💬", color: C.brand }].map((v, i) => (
              <div key={i} style={{ display: "flex", alignItems: "center", gap: 8, padding: "8px 14px", borderRadius: 4, border: `1px solid ${C.border1}`, backgroundColor: "white", fontSize: 12 }}>
                <span>{v.icon}</span>
                <span style={{ fontWeight: 700, color: v.color }}>{v.count}</span>
                <span style={{ color: C.text3 }}>{v.label}</span>
              </div>
            ))}
          </div>
        </div>

        <R1RightPanel
          comments={commentsState.status === "ready" ? commentsState.data : []}
          loading={commentsState.status === "loading"}
          errorMsg={commentsState.status === "error" ? commentsState.error : null}
        />
      </div>
    </div>
  );
}
